<?php
// Copyright FORTH-ICS, Emmanouil Dermitzakis
// -*- mode: php;-*-

function publication_mod_help($path, $arg) {
  switch ($path) {
    case "admin/help#publication_mod":
      return '' . t("Provides publication management system") . '';
      break;
  }
}

function publication_mod_menu(){
  $menu['ajax/add_publication_page'] = array(
    'title' => '',
    'page callback' => 'publication_mod_ajax_callback',
    // 'page arguments' => array(2),
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'type' => MENU_CALLBACK
  );

  $menu['ajax/get_path_from_uuid'] = array(
    'title' => '',
    'page callback' => 'publication_mod_ajax_callback_get_path',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'type' => MENU_CALLBACK
  );

  $menu['ajax/edit_publication_page'] = array(
    'title' => '',
    'page callback' => 'publication_mod_ajax_callback_edit_pub',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'type' => MENU_CALLBACK
  );

  $menu['ajax/update_pub_pages'] = array(
    'title' => '',
    'page callback' => 'publication_mod_update_pubs',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'type' => MENU_CALLBACK
  );

  $menu['admin/config/publications'] = array(
    'title' => 'Publications',
    'description' => 'Publications Description',
    'position' => 'right',
    'weight' => -12,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $menu['admin/config/publications/publication_mod'] = array(
    'title' => 'PRESS Publication Module',
    'description' => 'Configuration for PRESS Publication Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_mod_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
    // 'type' => MENU_NORMAL_ITEM,
  );

  $menu['admin/config/publications/publication_mod/default'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'PRESS Publication Module',
    'weight' => 1,
    // 'type' => MENU_NORMAL_ITEM,
  );

  $menu['admin/config/publications/publication_mod/external_authors'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Edit External Authors',
    'weight' => 2,
    'page callback' => '_external_authors_edit',
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
  );

  $menu['admin/config/publications/publication_mod/projects'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Edit Projects',
    'weight' => 3,
    'page callback' => '_projects_edit',
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
  );

  $menu['admin/config/publications/publication_mod/tags'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Edit Tags',
    'weight' => 4,
    'page callback' => '_tags_edit',
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
  );

  $menu['admin/config/publications/publication_mod/import_pubs'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Import Blazegraph Publications',
    'weight' => 5,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_mod_import_pubs_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
  );

  $menu['admin/config/publications/publication_mod/edit_orgs'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Edit Organizations',
    'weight' => 6,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('publication_mod_edit_orgs_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'publication_mod.admin.inc',
  );

  $menu['admin/config/publications/publication_mod/import_pubs/progress'] = array(
    'title' => t('Import progress'),
    'page callback' => 'publication_mod_import_progress',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'publication_mod.admin.inc',
  );


  $menu_links = [];
  $parent_link = array(
    'link_path' => 'publication/search-pub',
    'link_title' => 'Publications',
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
    'weight' => -5
  );
  $current_links = menu_load_links('main-menu');
  $found = FALSE;
  $mlid = 0;
  foreach ($current_links as $current) {
    if($parent_link['link_path'] === $current['link_path'] &&
        $parent_link['link_title'] === $current['link_title']){
      $found = TRUE;
      $mlid = $current['mlid'];
    }
  }

  if (!$found){
    $mlid = menu_link_save($parent_link);
  }

  $menu['publication/edit'] = array(
    'title' => 'Edit Publication',
    // 'type' => MENU_LOCAL_TASK,
    'description' => 'Edit a Publication',
    'page callback' => 'publication_mod_edit_publication',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'file' => 'publication_mod.pages.inc',
  );

  $menu['publication/add-pub'] = array(
    'title' => 'Add New Publication',
    'description' => 'Add New Publication',
    'page callback' => 'publication_mod_add_publication',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('authenticated user'),
    'file' => 'publication_mod.pages.inc',
  );

  $menu['publication/all'] = array(
    'title' => 'All Publications',
    'description' => 'All Publications',
    'page callback' => 'publication_mod_all_publications',
    'access callback' => TRUE,
    'file' => 'publication_mod.pages.inc',
  );

  $menu['publication/author/%'] = array(
    'title' => "Author's Publications",
    'description' => 'Publications of an Author',
    'page callback' => 'publication_mod_author_publications',
    'page arguments' => array(),
    'access callback' => TRUE,
    'file' => 'publication_mod.pages.inc',
  );

  $menu_links[0] = array(
    'link_path' => 'publication/add-pub',
    'link_title' => 'Add Publication',
    'menu_name' => 'main-menu',
    'plid' => $mlid,
    'weight' => 1
  );

  $menu['publication/search-pub'] = array(
    'title' => 'Search Publication',
    'description' => 'Search for Publications',
    'page callback' => 'publication_mod_search_publication',
    'access callback' => TRUE,
    'file' => 'publication_mod.pages.inc',
  );

  $menu_links[1] = array(
    'link_path' => 'publication/search-pub',
    'link_title' => 'Search Publication',
    'menu_name' => 'main-menu',
    'plid' => $mlid,
    'weight' => 0
  );

  $menu['press/add-project'] = array(
    'title' => 'Add Project',
    'description' => 'Add Project',
    'page callback' => 'publication_mod_add_project',
    'access callback' => 'publication_mod_user_has_role',
    'access arguments' => array('Publication Mod Power User'),
    'file' => 'publication_mod.pages.inc',
  );

  $menu_links[2] = array(
    'link_path' => 'press/add-project',
    'link_title' => 'Add Project',
    'menu_name' => 'main-menu',
    'weight' => -4
  );

  foreach ($menu_links as $link) {
    $found = FALSE;
    foreach ($current_links as $current) {
      if($link['link_path'] === $current['link_path'] &&
          $link['link_title'] === $current['link_title']){
        $found = TRUE;
      }
    }
    if (!$found){
      menu_link_save($link);
    }
  }
  menu_cache_clear_all();

  return $menu;
}

function _publication_mod_get_blazegraph_info($keys){
  $or = db_or();
  // $or->condition('pm_key', 'blazegraph_url');
  // $or->condition('pm_key', 'blazegraph_prefix');
  // $or->condition('pm_key', 'blazegraph_orgs');
  foreach ($keys as $key) {
    $or->condition('pm_key', $key);
  }
  $result = db_select('publication_mod', 'pm')
    ->fields('pm', array('pm_key', 'pm_value'))
    ->condition($or)
    ->execute()
    ->fetchAllKeyed();

  return $result;
}

function publication_mod_menu_local_tasks_alter(&$data, $router_item, $root_path){
  if (substr($root_path, 0, 5) === 'node/'){
    foreach ($router_item['page_arguments'] as $key => $argument) {
      if (is_object($argument) && array_key_exists('type', $argument) && $argument->type == 'publication_mod_publications') {
        foreach ($data['tabs'][0]['output'] as $key => $value) {
          if (!publication_mod_user_has_role('administrator') && $value['#link']['path'] === 'node/%/edit') {
            unset($data['tabs'][0]['output'][$key]);
          }
        }

        if (publication_mod_user_has_role('authenticated user') && $argument->pub_mod_field_category){
          if($argument->pub_mod_field_blazegraph_uuid){
            $uuid = $argument->pub_mod_field_blazegraph_uuid['und'][0]['value'];
          }else{
            $uuid = $argument->uuid;
          }
          $data['tabs'][0]['output'][] = array(
            '#theme' => 'menu_local_task',
            '#link' => array(
              'title' => t('Edit Publication'),
              'href' => 'publication/edit',
              'access callback' => 'publication_mod_user_has_role',
              'access arguments' => array('authenticated user'),
              'localized_options' => array(
                'query' => array(
                  'uuid' => $uuid,
                  'category' => $argument->pub_mod_field_category['und'][0]['value']
                ),
                'html' => TRUE
              )
            )
          );
        }
        $data['tabs'][0]['count'] = count($data['tabs'][0]['output']);
      }
    }
  }else if(substr($root_path, 0, 5) === 'user/'){
    watchdog('publication_mod', 'local_tasks: root_path: %root_path <br/> $data: <pre> %data </pre><br/> router_item: <pre> %router_item </pre>', array('%root_path' => $root_path, '%data'=>print_r($data, true), '%router_item' => print_r($router_item, true)), WATCHDOG_DEBUG);
    $uuid = $router_item['page_arguments'][0]->pub_mod_field_blazegraph_uuid['und'][0]['value'];
    if(uuid_is_valid($uuid)){
      $uuid = "urn:uuid:" . $uuid;
    }
    $name = $router_item['page_arguments'][0]->pub_mod_field_first_name['und'][0]['value'];
    $data['tabs'][0]['output'][] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t($name .'\'s Publications'),
        'href' => 'publication/search-pub',
        // 'access callback' => 'publication_mod_user_has_role',
        // 'access arguments' => array('authenticated user'),
        'localized_options' => array(
          'query' => array(
            'type' => 'advanced',
            'reviewed' => 'false',
            'authors0' => $uuid,
          ),
          'html' => TRUE
        )
      )
    );
  }
}

function _publication_mod_create_page_body($pub_uri){
  global $base_url;
  $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_url', 'blazegraph_prefix'));
  $dbURL = $blazegraph_info['blazegraph_url'];
  $ontologyPrefix = $blazegraph_info['blazegraph_prefix'];

  // $query = 'prefix press: <'. $ontologyPrefix. '>
  //           select * where{
  //             BIND (<'. $pub_uri .'> as ?pub).
  //             ?pub ?p ?o.
  //             ?p rdf:type owl:DatatypeProperty.
  //             FILTER(?p != press:CreationDate && ?p != press:ModifiedDate && ?p != press:Publication_UUID).
  //             ?p rdfs:label ?plabel.
  //           }';

  $query = 'prefix press: <'. $ontologyPrefix. '>
            select * where{
              BIND (<'. $pub_uri .'> as ?pub).
              ?pub ?p ?o.
              optional{?p rdf:type ?type}.
              FILTER(?p = rdf:type || (?p != press:CreationDate && ?p != press:ModifiedDate && ?p != press:Publication_UUID && ?type = owl:DatatypeProperty)).
              OPTIONAL{?p rdfs:label ?plabel}.
            }';

  $q = http_build_query(array('query' => $query));

  $options = array(
    'headers' => array(
      'Accept'=>'application/sparql-results+json',
      'content-type'=> 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => $q
  );

  $result = drupal_http_request($dbURL, $options);

  //Get Pub's contributors
  $query = 'prefix press: <'. $ontologyPrefix. '>
          select * where{
            BIND (<'. $pub_uri .'> as ?pub).
            ?pub press:hasContributor ?slot.
            ?slot press:list_index ?index.
            ?con_type rdfs:subPropertyOf* press:contributorType.
            ?slot ?con_type ?con.
            ?con foaf:givenName ?givenName.
            ?con foaf:familyName ?familyName.
            ?con_type rdfs:label ?con_type_label.
          }';

  $q = http_build_query(array('query' => $query));

  $options = array(
    'headers' => array(
      'Accept'=>'application/sparql-results+json',
      'content-type'=> 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => $q
  );

  $contributor_results = drupal_http_request($dbURL, $options);
  $contributor_json = json_decode($contributor_results->data);

  //Create Contributor bar
  $html = '<div>';
  $contributors = array();
  foreach($contributor_json->results->bindings as $con){
    if(!array_key_exists($con->con_type_label->value, $contributors)){
      $contributors[$con->con_type_label->value] = array();
    }
    $contributors[$con->con_type_label->value][$con->index->value] = array(
      "name" => $con->givenName->value . ' ' . $con->familyName->value,
      "uri" => $con->con->value
    );
  }
  $contributors_html = '<div class="col-sm-12">';
  foreach($contributors as $con_type=>$cons){
    $concat = '<div class="col-sm-3"><h3>' . $con_type . '</h3>';
    ksort($cons); 
    foreach($cons as $key=>$con){
      $concat .= '<a target="_blank" data-index="'. $key .'" href="'. $base_url . 
        '/publication/search-pub?type=advanced&reviewed=false&authors0='. 
        urlencode($con['uri']) .'">'. $con['name'] . '</a><br/>';
    }

    $concat .= '</div>';
    $contributors_html .= $concat;
  }
  $contributors_html .= '</div>';

  $html .= $contributors_html;

  //Create Abstract if exists & Array of Data properties

  $dataAttributes = json_decode($result->data);
  $abstracts = '<div class="col-sm-12">';
  $abstractExists = false;
  $summary = '';
  $restFields = '<div class="col-sm-12"><p>&nbsp;</p><table class="table table-hover">';
  $title = '';
  $pub_type = '';
  foreach ($dataAttributes->results->bindings as $value) {
    if($value->p->value === 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'){
      $pub_type = explode("#", $value->o->value)[1];
      break;
    }
  }
  $tags = '<tr><td>Tags</td><td>';
  $tagsExist = false;
  foreach($dataAttributes->results->bindings as $d){
    if($d->p->value == 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'){
      continue;
    }
    if(strpos($d->plabel->value, 'Abstract') !== false){
      $abstractExists = true;
      $abstract ='<div class="col-sm-12"><h3>'. $d->plabel->value  .'</h3><p>'. $d->o->value . '</p></div>';
      $abstracts .= $abstract;
      
    }elseif ($d->plabel->value == 'Tags') {
      if($tagsExist){
        $tags .= ', ';
      }else{
        $tagsExist = true;
      }
      $tags .= '<a href="/publication/search-pub?type=advanced&reviewed=false&tags0=' . $d->o->value .'" target="_blank">'. $d->o->value . '</a>';
    }
    else{
      $oValue = $d->o->value;
      if(filter_var($d->o->value, FILTER_VALIDATE_URL)){
        $oValue = '<a href="'. $d->o->value . '" target="_blank">' . $d->o->value . '</a>';
      }else{
        if($d->plabel->value == 'DOI'){
          $oValue = '<a href="https://doi.org/'. $d->o->value . '" target="_blank">' . $d->o->value . '</a>';
        }
      }
      $restFields .= '<tr><td>' . $d->plabel->value . '</td><td>'. $oValue . '</td></tr>';
    }

    if (strpos($d->plabel->value, 'Title') !== false) {
      $title_type = explode("#", $d->p->value)[1];
      switch ($pub_type) {
        case 'Edited_proceeding':
        case 'Editor':
        case 'Whole_book':
        case 'Monograph':
          if($title_type == 'Book_Title'){
            $title = $d->o->value;
          }
          break;
        case 'Chapter_in_book':
          if($title_type == 'Chapter_Title'){
            $title = $d->o->value;
          }
          break;
        default:
          if($title_type == 'English_Title'){
            $title = $d->o->value;
          }
          break;
      }
    }
  }

  $tags .= '</td>';
  if($tagsExist){
    $restFields .= $tags;
  }

  $restFields .= '</table></div>';
  $abstracts .= '</div>';
  if($abstractExists){
    $html .= $abstracts;
  }

  $html .= $restFields;

  //Max length of Drupal Title is 128
  $length = 0;
  if(strlen($title)>128){
    $titles = explode(' ', $title);
    $title = '';
    foreach($titles as $t){
      if(strlen($title) < 125 && strlen($title. ' ' . $t) >= 125){
        $title .= '...';
        break;
      }else{
        if(strlen($title)>0){
          $title .= ' ';
        }
        $title .= $t;
      }
    }
  }

  return array('title'=>$title, 'html'=>$html, 'summary'=> $summary, 'category'=>$pub_type);
}

/**
 * Checks if use has one of the roles in arguments
 * @return type
 */
function publication_mod_user_has_role(){
  global $user;
  $roles = func_get_args();
  foreach($roles as $role){
    if (in_array($role, $user->roles)){
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Returns user information
 * @return string
 */
function _get_user_info_to_json(){
  global $user;

  $current_user = '';
  if (!user_is_anonymous()){
    $user_data = user_load($user->uid); //TODO Fix Anonymous
    $current_user = $current_user . "{uuid: '". $user_data->uuid . "', name:'" .
          $user_data->pub_mod_field_first_name['und'][0]['value'] . " " .
          $user_data->pub_mod_field_last_name['und'][0]['value'] . "', mail:'" .
          $user_data->mail . "', lab: '" .
          $user_data->pub_mod_field_organization['und'][0]['option'] ."', roles: ";
    $current_user = $current_user . "[";
    foreach($user->roles as $value){
      $current_user = $current_user . "'". $value . "',";
    }
    $current_user = $current_user . "]}";
  }else{
    $current_user = "{anonymous:true}";
  }
  return $current_user;
}

/**
 * Returns lab information
 * @return string
 */
function _get_labs_to_json(){
  $labs = '';
  $labs = $labs . "{";
  $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_orgs'));
  $orgs = array();
  $blazegraph_orgs = explode("\n", $blazegraph_info['blazegraph_orgs']);
  foreach ($blazegraph_orgs as $org) {
    if($org != ""){
      $org_info = explode('|', $org);
      $key = trim($org_info[0]);
      $bg_value = trim($org_info[1]);
      $orgs[$bg_value] = $key;
    }
  }
  foreach($orgs as $key => $value){
    $labs = $labs . "'". $value . "':'" . $key . "',";
  }
  $labs = $labs . "}";

  return $labs;
}

function _add_presslib_library(){
  $module_path = drupal_get_path('module', 'publication_mod');

  drupal_add_js($module_path . '/js/typeahead.bundle.js');
  drupal_add_js($module_path . '/js/Sortable.js');
  drupal_add_js($module_path . '/js/moment.min.js');
  drupal_add_js($module_path . '/js/daterangepicker.js');
  drupal_add_js($module_path . '/js/pressfields.js');
  drupal_add_js($module_path . '/js/presslib.js');
  drupal_add_js($module_path . '/js/pressSearch.js');
  drupal_add_js($module_path . '/js/pressExternalAuthors.js');
  drupal_add_js($module_path . '/js/pressEditProjects.js');
  drupal_add_js($module_path . '/js/pressEditTags.js');
  drupal_add_js($module_path . '/js/jquery.twbsPagination.js');
  drupal_add_js($module_path . '/js/pressProjects.js');

  drupal_add_css($module_path . "/css/presslib.css");
  drupal_add_css($module_path . "/css/typeaheadjs.css");
  drupal_add_css($module_path . "/css/sortable.css");
  drupal_add_css($module_path . "/css/daterangepicker.css");
}


/*
 * Handles the new publication addition.
 */
function publication_mod_ajax_callback($title='', $category='', $body='', $summary='', $uuid=''){
  global $user;
  $function_called = true;
  if(empty($title) && empty($category) && empty($body)){
    $title = $_POST['title'];
    $category = $_POST['category'];
    $body = $_POST['body'];
    $summary = $_POST['summary'];
    $function_called = false;
  }
  // $values = explode("&", $value);
  // print_r($values);
  // $vals;
  // $i=0;
  // foreach($values as $val){
  //   $vals[$i++] = explode("=", $val);
  // }
  // print_r($vals);
  // echo "<br />";
  // print_r($_POST);
  // echo "<br />";
  // print_r($_FILES);
  // return;

  // entity_create replaces the procedural steps in the first example of
  // creating a new object $node and setting its 'type' and uid property
  $values = array(
    'type' => 'publication_mod_publications',
    'uid' => $user->uid,
    'status' => 1,
    'comment' => 0,
    'promote' => 1,
  );
  $entity = entity_create('node', $values);

  // The entity is now created, but we have not yet simplified use of it.
  // Now create an entity_metadata_wrapper around the new node entity
  // to make getting and setting values easier
  $ewrapper = entity_metadata_wrapper('node', $entity);

  // Using the wrapper, we do not have to worry about telling Drupal
  // what language we are using. The Entity API handles that for us.
  // $ewrapper->format->set('ace_editor');

  $ewrapper->title->set($title);

  $ewrapper->pub_mod_field_category->set($category);

  if(isset($uuid)){
    $ewrapper->pub_mod_field_blazegraph_uuid->set($uuid);
  }
  // Setting the body is a bit different from other properties or fields
  // because the body can have both its complete value and its
  // summary
  $my_body_content = $body;
  $ewrapper->body->set(array('value' => $my_body_content, 'format' => 'full_html'));
  if(isset($summary)){
    $ewrapper->body->summary->set($summary);
  }

  // Setting the value of an entity reference field only requires passing
  // the entity id (e.g., nid) of the entity to which you want to refer
  // The nid 15 here is just an example.
  // $ref_nid = 15;
  // Note that the entity id (e.g., nid) must be passed as an integer not a
  // string
  // $ewrapper->field_my_entity_ref->set(intval($ref_nid));

  // Now just save the wrapper and the entity
  // There is some suggestion that the 'true' argument is necessary to
  // the entity save method to circumvent a bug in Entity API. If there is
  // such a bug, it almost certainly will get fixed, so make sure to check.
  $file_path = "";
  if (array_key_exists("myfile", $_FILES) && file_exists($_FILES['myfile']['tmp_name']) && is_uploaded_file($_FILES['myfile']['tmp_name'])){
    $path = $_FILES['myfile']['tmp_name'];
    $filename = $_FILES['myfile']['name'];

    $file_temp = file_get_contents($path);

    $file_temp = file_save_data($file_temp, 'public://publication_mod_publications/' . $filename, FILE_EXISTS_RENAME);

    $entity->field_file = array(
      'und' => array(
          0 => array(
            'fid' => $file_temp->fid,
            'filename' => $file_temp->filename,
            'filemime' => $file_temp->filemime,
            'uid' => $user->uid,
            'uri' => $file_temp->uri,
            'status' => 1,
            'display' => 1
          )
        )
      );
    $file_real_path;
    if($fwrapper = file_stream_wrapper_get_instance_by_uri($file_temp->uri)){
      $file_real_path = $fwrapper->realpath();
      $file_path = str_replace($_SERVER['DOCUMENT_ROOT'].'/','',$file_real_path);
    }
  }
  $ewrapper->save();
  header('Content-Type: application/json');
  $ewrapper->pub_mod_field_blazegraph_uuid->set($ewrapper->value()->uuid);
  $ewrapper->save();
  $result = array(
    'uuid' => $ewrapper->value()->uuid,
    'path' => drupal_get_path_alias("node/" . $ewrapper->value()->nid, null),
    'file_url' => $file_path
  );

  if($function_called){
    return $result;
  }
  echo json_encode($result, true);
  return;
  // echo $ewrapper->value()->uuid;
  // echo '<br/>';
  // echo drupal_get_path_alias("node/" . $ewrapper->value()->nid, null);
}

function publication_mod_update_pubs($blazegraph_uris = array()){
  if(empty($blazegraph_uris)){
    $blazegraph_uris = $_POST['blazegraph_uris'];
    $function_called = false;
  }

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'publication_mod_publications')
    ->fieldCondition('pub_mod_field_blazegraph_uuid', 'value', $blazegraph_uris, 'IN');

  $result = $query->execute();

  if (isset($result['node'])){
    $ids = array_keys($result['node']);
  }else{
    return;
  }

  foreach($ids as $id){
    $entity = node_load($id);
    $pub_page = _publication_mod_create_page_body($entity->pub_mod_field_blazegraph_uuid['und'][0]['value']);

    $entity->title= $pub_page['title'];
    $entity->body['und'][0]['value'] = $pub_page['html'];
    $entity->body['und'][0]['summary'] = $pub_page['summary'];
    $entity->pub_mod_field_category['und'][0]['value'] = $pub_page['category'];
    node_save($entity);
  }
  http_response_code(200);
  return;
}

function publication_mod_ajax_callback_edit_pub(){
  global $user;

  $uuid = $_POST['uuid'];
  $delete = false;
  if (array_key_exists("delete", $_POST)){
    if ($_POST['delete'] === 'true'){
      $delete = true;
    }
  }

  if ($delete === false){
    $body_content = $_POST['body'];
    $title = $_POST['title'];
    $summary = $_POST['summary'];
    $category = $_POST['category'];
  }

  $file_path = '';

  $ewrappers;
  $entity = null;

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'publication_mod_publications')
    ->fieldCondition('pub_mod_field_blazegraph_uuid', 'value', $uuid, '=');

  $result = $query->execute();

  if (isset($result['node']) && count($result['node']) == 1){
    $ids = array_keys($result['node']);
    $entity = node_load($ids[0]);
  }else{
    $ewrappers = array();
  }
  echo $delete;
  if ($delete){
    if ($entity)
      node_delete($entity->nid);

    return;
  }

  $ewrapper;

  $entity->title= $title;
  $entity->body['und'][0]['value'] = $body_content;
  $entity->body['und'][0]['summary'] = $summary;
  $entity->pub_mod_field_category['und'][0]['value'] = $category;
  // echo print_r($ewrapper);

  if (array_key_exists("myfile", $_FILES) &&    //If file exists, update it
      file_exists($_FILES['myfile']['tmp_name']) &&   //TODO does it delete it?
      is_uploaded_file($_FILES['myfile']['tmp_name'])){

    $path = $_FILES['myfile']['tmp_name'];
    $filename = $_FILES['myfile']['name'];

    $file_temp = file_get_contents($path);

    $file_temp = file_save_data($file_temp, 'public://publication_mod_publications/' . $filename, FILE_EXISTS_RENAME);

    $entity->field_file = array(
      'und' => array(
          0 => array(
            'fid' => $file_temp->fid,
            'filename' => $file_temp->filename,
            'filemime' => $file_temp->filemime,
            'uid' => $user->uid,
            'uri' => $file_temp->uri,
            'status' => 1,
            'display' => 1
          )
        )
      );
  }
  // print_r($ewrapper->field_file->raw());
  $file_real_path;
  if($entity->field_file && $fwrapper = file_stream_wrapper_get_instance_by_uri($entity->field_file['und'][0]['uri'])){
    $file_real_path = $fwrapper->realpath();
    $file_path = str_replace($_SERVER['DOCUMENT_ROOT'].'/','',$file_real_path);
  }
  entity_get_controller('node')->resetCache(array(entity_id('node', $entity)));
  field_attach_update('node', $entity);

  node_save($entity);

  header('Content-Type: application/json');
  $result = array(
    'uuid' => $entity->uuid,
    'path' => drupal_get_path_alias("node/" . $entity->nid, null),
    'file_url' => $file_path
  );

  echo json_encode($result, true);
  exit();
}

/*
 * Returns the path alias by uuid.
 */
function publication_mod_ajax_callback_get_path(){
  $uuid = $_GET['uuid'];

  $ewrappers = entity_uuid_load('node', array($uuid));
  $result = array();
  $i = 0;
  foreach($ewrappers as $key => $entity){
    $result[$uuid] = array(
      'uuid' => $uuid,
      'path' => drupal_get_path_alias("node/" . $entity->nid, null)
    );
  }

  echo json_encode($result, true);
  exit();
}


// Custom Laboratory Field Type
/**
 * Impllements hook_field_info().
 * @return array
 */

function publication_mod_field_info(){
  return array(
    'pub_mod_organization' => array(
      'label' => t('Publication Mod Organization'),
      'description' => t('User Organization Field'),
      'settings' => array('max_length' => 255),
      'instance_settings' => array(
        'text_processing' => 0,
      ),
      'default_widget' => 'options_select',
      'default_formatter' => 'pub_mod_organization_formatter',
    )
  );
}


/**
 * Implements hook_field_is_empty().
 * 
 */
function publication_mod_field_is_empty($item, $field) {
  return (empty($item['option'])) ;
}

/**
 * Implements hook_field_widget_info_alter
 * @param type &$info 
 * @return type
 */
function publication_mod_field_widget_info_alter(&$info){
  $widgets = array(
    'options_select' => array('pub_mod_organization'),
  );

  foreach($widgets as $widget => $field_types){
    $info[$widget]['field types'] = array_merge($info[$widget]['field types'], $field_types);
  }
}

function publication_mod_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors){
  foreach ($items as $delta => $item) {
    if(!(empty($item['option']))){
      // if(!preg_match('([A-Za-z0-9_])+', $item['option'])){
        // $errors[$field['field_name']][$langcode][$delta][] = array(
        //   'error' => 'pub_mod_field_invalid',
        //   'message' => t('Lab Value must be one word and contain letters, numbers and _')
        // );
      // }
    }
  }
}

function publication_mod_options_list($field, $instance, $entity_type, $entity){

  $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_orgs'));
  /*$dbURL = $blazegraph_info['blazegraph_url'];
  $ontologyPrefix = $blazegraph_info['blazegraph_prefix'];

  $query = 'prefix press:<' . $ontologyPrefix .'>'.
'select ?org ?org_name where{'.
  '?org rdf:type press:Organization;'.
       'press:Organization_Name ?org_name.'.
'}';

  $q = http_build_query(array('query' => $query));

  $options = array(
    'headers' => array(
      'Accept'=>'application/sparql-results+json',
      'content-type'=> 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => $q
  );

  $result = drupal_http_request($dbURL, $options);

  $data = json_decode($result->data);
  $options = array();*/

  // foreach($data->results->bindings as $org){
  //   $options[$org->org->value] = $org->org->value;  //TODO CHANGE
  // }

  $orgs = explode("\n", $blazegraph_info['blazegraph_orgs']);
  $options = array();
  foreach ($orgs as $org) {
    if($org != ""){
      $org_info = explode('|', $org);
      $key = trim($org_info[0]);
      $bg_value = trim($org_info[1]);

      $options[$bg_value] = $key;
    }
  }


  return $options;
}

function publication_mod_field_formatter_info(){
  return array(
    'pub_mod_organization_formatter' => array(
      'label' => t('Default Formatter'),
      'field types' => array('pub_mod_organization')
    )
  );
}

function publication_mod_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  //Currently we only have one display option, use switch
  //to prepare for future options.
  switch ($display['type']) {
    case 'pub_mod_organization_formatter':
      $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_orgs'));
      $orgs = explode("\n", $blazegraph_info['blazegraph_orgs']);
      $options = array();
      foreach ($orgs as $org) {
        if($org != ""){
          $org_info = explode('|', $org);
          $key = trim($org_info[0]);
          $bg_value = trim($org_info[1]);

          $options[$bg_value] = $key;
        }
      }
      foreach ($items as $delta => $item) {
        if (isset($item['option'])) {
          $output = field_filter_xss($options[$item['option']]);
        }
        else {
          $output = "Not Supplied";
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;
    default:
  }
  return $element;
}


function publication_mod_feeds_processor_targets_alter(&$targets, $entity_type, $bundle){
  if ($entity_type == 'user' && $bundle == 'user'){
    foreach(field_info_instances($entity_type, $bundle) as $name => $instance){
      $info = field_info_field($name);
      unset($callback);

      if ($info['type'] == 'pub_mod_organization'){
        $callback = 'publication_mod_target_setter';
      }

      if(isset($callback)){
        $targets[$name] = array(
          'name' => check_plain($instance['label']),
          'callback' => $callback,
          'description' => t('The @label field of the node.', array('@label' => $instance['label']))
        );
      }
    }
  }
}

function publication_mod_target_setter($source, $entity, $target, $values, $mapping){
  watchdog('publication_mod', 'target: %target <br> value: %value<br>mapping: %mapping', 
    array(
      '%target' => print_r($target, true),
      '%value' => print_r($values, true), 
      '%mapping' => print_r($mapping, true)
    ), WATCHDOG_DEBUG);

  if(empty($values)){
    return;
  }

  if(!is_array($values)){
    $values = array($values);
  }
  $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_orgs'));
  $orgs = explode("\n", $blazegraph_info['blazegraph_orgs']);
  $options = array();
  foreach ($orgs as $org) {
    if($org != ""){
      $org_info = explode('|', $org);
      $key = trim($org_info[0]);
      $bg_value = trim($org_info[1]);
      $accepted_values = array_map('trim', explode(",", trim($org_info[2], " \t\n\r\0\x0B[]")));
      foreach ($accepted_values as $a_value) {
        $options[$a_value] = array('key' => $key, 'value' => $bg_value);
      }
    }
  }
  watchdog('publication_mod', 'a_value: "%a_value"', 
    array(
      '%a_value' => print_r($options[$values[0]], true),
    ), WATCHDOG_DEBUG);

  $entity->{$target}['und'][0]['option'] = $options[$values[0]]['value'];
}


// On user insert & update

function publication_mod_user_presave(&$edit, $account, $category){

  $blazegraph_info = _publication_mod_get_blazegraph_info(array('blazegraph_prefix', 'blazegraph_url', 'blazegraph_orgs'));

  $orgs = explode("\n", $blazegraph_info['blazegraph_orgs']);
  $orgoptions = array();
  foreach ($orgs as $org) {
    if($org != ""){
      $org_info = explode('|', $org);
      $key = trim($org_info[0]);
      $bg_value = trim($org_info[1]);
      $accepted_values = array_map('trim', explode(",", trim($org_info[2], " \t\n\r\0\x0B[]")));
      $orgoptions[$key] = $bg_value;
    }
  }

  $prefix = $blazegraph_info['blazegraph_prefix'];
  $blazegraph_url = $blazegraph_info['blazegraph_url'];

  $sparql = "prefix foaf: <http://xmlns.com/foaf/0.1/>".

  "DELETE {<urn:uuid:". $account->uuid . "> ?p ?o} WHERE {".
    "<urn:uuid:". $account->uuid."> ?p ?o".
  "};".
  "INSERT DATA{".
    "<urn:uuid:". $account->uuid."> rdf:type foaf:Person;".
    "<". $prefix ."Person_UUID> \u0022urn:uuid:" . $account->uuid. "\u0022;".
    "foaf:familyName \u0022". $account->pub_mod_field_last_name['und'][0]['value'] ."\u0022;" .
    "foaf:givenName \u0022" . $account->pub_mod_field_first_name['und'][0]['value'] ."\u0022;".
    "<". $prefix ."Person_Group> \u0022FORTH_ICS_Author\u0022;".
    "foaf:mbox \u0022mailto:". $account->mail . "\u0022;".
    "<". $prefix ."memberOf> <". $prefix . "Organization/" .$account->pub_mod_field_organization['und'][0]['option'] .">." .
  "}";

  $edit['pub_mod_field_blazegraph_uuid']['und'][0]['value'] = $account->uuid;

  $q = http_build_query(array('update' => $sparql));

  $options = array(
    'headers' => array(
      'Accept'=>'html',
      'content-type'=> 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => $q
  );

  $result = drupal_http_request($blazegraph_url, $options);


  watchdog("Blazegraph Person Creation", print_r($result, true), array(), WATCHDOG_NOTICE);
}